### PR TITLE
Total rewrite to improve performance and fit customer workflow.

### PR DESCRIPTION
**Pull request by thaljef**
* Renamed vars & functions to improve readability. Also reorganized
  functions and added whitespace to improve readability.
* Improved performance by sorting components on the server and
  consuming through generators rather than slurping them all at once.
* Added limits when searching for copyrights in older components. If
  you can't find a copyright in the last 10 versions, your're probably
  never going to find them.
* Added filtering to remove duplicate copyrights (after normalizing
  whitespace and lettercase).
* Format output to match the existing Notices report, so it has a
  familiar human-readable appearance.
* Added exception handling to cover connection failures, unexpected
  data structures from the API, and other edge cases.

### CODE REVIEW

**Comment by skiyooka** [comment]
Thank you for doing all this work! Although I did not contribute at all to the original script looks good from my end.

**Comment by thaljef** [comment]
I neglected to update the documentation and README. I’ll do that later today.

**Comment by mkumykov** [comment]
@thaljef this version of the script departs quite a bit fron the original one. primarily in functionality reduction and applicability for automation. Not a showstopper, by any means. If customers is satisfied with the result, I see no  problem switching to this version.

**Comment by thaljef** [comment]
@mkumykov , yes it's quite a bit simpler. Merely replicates the copyright section of the notices report. The idea is to just stick this into the build process to generate a COPYRIGHT file that is included in the final binary release artifact.

**Pull request merged**
