### PR TITLE
Gsnyder/extended client

### PR DESCRIPTION
**Pull request by gsnyder2007**
A proposal to extend the Client interface and add methods for common operations like getting a project by its name or getting a project-version using the project and version names. If this proposal is accepted we can proceed to populate other convenience methods that will reduce the amount of boilerplate code people have to use to retrieve and work with the BD REST objects.

### CODE REVIEW

**Comment by mkumykov** [comment]
Ah! I miss come convenient calls from HubInstance. 
We had to come a full circle at some point and reimplement something like that using new Client class.
Cool!

**Comment by gsnyder2007** [comment]
> Big question is how much of this kind of functionality we are expecting to be implemented.
> Are we looking at somewhat more elegant re-implementation of HubInstance?

Yes, that is where this PR is headed although I only implemented two for fetching project and project-version objects by their name for now. Maybe add more later?

**Comment by skiyooka** [comment]
Client has been strictly with generic methods that apply across the entire REST API. Is "get_by_name" generic enough that it can be implemented in such a manner?

**Comment by gsnyder2007** [comment]
> > Client has been strictly with generic methods that apply across the entire REST API. Is "get_by_name" generic enough that it can be implemented in such a manner?
> 
> Or perhaps even `get_resource_by`?
> 
> ```
>    # untested hypothetical 
>     def get_resource_by(self, field, value,  name, parent=None, **kwargs):
>         params = {
>             'q': [f"{field}:{value}"]
>         }
>         filtered = [i for i in self.get_resource(name, parent, params=params) if i.get(field) == value]
>         assert len(filtered) in [0,1], f"We either found the {field} or we didn't, but we should never find this many ({len(filtered)})"
> 
>         return filtered[0] if filtered else None
> ```

Yeah, I was thinking about sometime similar that would be totally generic and still accomplish the same thing (i.e. make it easier to fetch common objects by their name). Let me go back and test some of these ideas and update the PR accordingly. Thanks.

**Comment by gsnyder2007** [comment]
Decided to close this one and resubmit with a diff proposal

**Pull request closed without merging**
