### PR TITLE
Github Security scanning of the Python code in the hub-rest-api-python

### PR DESCRIPTION
**Pull request by avnes**
- Github Actions workflow for scanning Python code using Github CodeQL.

### CODE REVIEW

**Comment by AR-Calder** [comment]
Looks good, thanks for the PR. Personally think this would be a great addition - thoughts @skiyooka @gsnyder2007 ?

**Comment by skiyooka** [comment]
I am open to scanning this repo. I'll only have cycles to address vulnerabilities in the new Client. As for vulns in HubRestApi I suggest a strategy of triage starting with the highest criticality but no guarantee of what will be addressed.

**Comment by avnes** [comment]
So anyone that want to review and potentially approve this PR given the positive feedback above?

**Comment by avnes** [comment]
Who can merge this PR please? (I don't have write access)

**Pull request merged**
