### PR TITLE
Correct indentation and trailing whitespace. Fixes #97.

### LINKED ISSUE #97: Latest code broken due to inconsistent indentation
`Traceback (most recent call last):
  File "./download-reports.py", line 11, in <module>
    from blackduck.HubRestApi import HubInstance
  File "/home/couchbase/jenkins/workspace/blackduck-reports/build-tools/blackduck/jenkins/generate-reports/.venv/lib/python3.6/site-packages/blackduck/HubRestApi.py", line 1685
    def get_matched_components(self, version_obj, limit=9999):
                                                             ^
TabError: inconsistent use of tabs and spaces in indentation
`

### PR DESCRIPTION
**Pull request by ceejatec**

### CODE REVIEW

**Comment by ceejatec** [comment]
@mkumykov Please merge this (or something similar) ASAP - currently "pip install blackduck" results in a broken install.

**Comment by mkumykov** [comment]
@ceejatec 
Does not seem to be a problem, I can instal it and uninstall it without issues:
$ pip3 install blackduck
Collecting blackduck
  Downloading blackduck-0.0.47-py3-none-any.whl (21 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from blackduck) (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->blackduck) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->blackduck) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->blackduck) (2019.3.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->blackduck) (3.0.4)
Installing collected packages: blackduck
Successfully installed blackduck-0.0.47
$ pip3 uninstall blackduck 
Found existing installation: blackduck 0.0.47
Uninstalling blackduck-0.0.47:
  Would remove:
    /usr/local/lib/python3.7/site-packages/blackduck-0.0.47.dist-info/*
    /usr/local/lib/python3.7/site-packages/blackduck/*
Proceed (y/n)? y
  Successfully uninstalled blackduck-0.0.47
$

**Comment by mkumykov** [comment]
@ceejatec Could you post the error message you are getitng?

**Comment by ceejatec** [comment]
You can install it OK, but if you actually import it it will break:
% python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> from blackduck import HubRestApi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/.venv/lib/python3.8/site-packages/blackduck/HubRestApi.py", line 1685
    def get_matched_components(self, version_obj, limit=9999):
                                                             ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by ceejatec** [comment]
@mkumykov  See also the linked issue: #97

**Comment by mkumykov** [comment]
@ceejatec I see it.  I have it corrected in the code. Waiting for Glenn to push it to package repository.  Thanks for catching it.

**Comment by mkumykov** [comment]
@ceejatec Should be all set. Make sure pip pulls version 0.0.48  it has the fix.
Thanks

**Pull request closed without merging**
