### PR TITLE
Updated Koshmack/dev filtering notifications to address HTTP error handling

### PR DESCRIPTION
**Pull request by koshmack**
The suggested HTTP error handling for continued reading and updating the Notifications is added and tested. It is now ready to receive another round of review.

### CODE REVIEW

**Comment by nichollsdave** [comment]
If I read the changes to error handling correctly if there is an error at any point reading or updating the notifications then it will add one to the failure count, and try again and reload all notifications and start again.  Therefore if there is a constant problem it will get stuck in that while True loop.  I guess this is robust on one hand because it will keep trying but is there a point where you want it to give up, say after 100 errors?  Not saying we definitely want that just wondering what the requirement is, would you prefer it to keep trying until it succeeds (or keep trying for eternity)?

**Comment by OffBy0x01** [comment]
The defaults built into [HubSession ](https://github.com/blackducksoftware/hub-rest-api-python/blob/master/blackduck/Client.py#L24) should be sufficient for HTTP retry events, was there a specific error you encountered where this was not sufficient?

**Comment by koshmack** [comment]
Hi, after reading the comments for pull requested hub filtering_notifications.py and coming after the 2nd thought of mine, I would prefer to revert to the original error handling which only depends on the hub python API's embedded retry (default is 15 sec * 3 times). If the customer's network quality is not excellent, they could increase the timer or the retry count or both which are configurable in .restconfig-notifications.json file for the adjustment. Do you think that this is a reasonable conclusion? Thank you

**Comment by koshmack** [comment]
I will close this PR and will submit a new one where the error handling is reverted to the original one.

**Pull request closed without merging**
